default: &default
  #adapter: postgresql
  #encoding: unicode
  #pool: 5
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  #database: myapp_development
  database: db/development.sqlite3

test:
  <<: *default
  #database: myapp_test
  database: db/test.sqlite3

production:
  <<: *default
  #database: myapp_production
  database: db/production.sqlite3
